[package]
name = "pwd-gen-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
passwords = { version = "3.1.4", features = ["common-password"] }
